export const UPDATE_NEW_MESSAGE = 'UPDATE_NEW_MESSAGE';
export const CLEAR_NEW_MESSAGE = 'CLEAR_NEW_MESSAGE';
export const REQUEST_CLEAR_CHAT_BADGES = 'REQUEST_CLEAR_CHAT_BADGES';
export const RECEIVE_CLEAR_CHAT_BADGES = 'RECEIVE_CLEAR_CHAT_BADGES';
// export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
// export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
