export const UPDATE_NEW_MESSAGE = 'UPDATE_NEW_MESSAGE';
export const CLEAR_NEW_MESSAGE = 'CLEAR_NEW_MESSAGE';
// export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
// export const CLEAR_MESSAGES = 'CLEAR_MESSAGES';
