export const REQUEST_GET_CONTACTS = 'REQUEST_GET_CONTACTS';
export const RECEIVE_GET_CONTACTS = 'RECEIVE_GET_CONTACTS';
export const FAILURE_GET_CONTACTS = 'FAILURE_GET_CONTACTS';
export const REQUEST_GET_PHONE_CONTACTS = 'REQUEST_GET_PHONE_CONTACTS';
export const RECEIVE_GET_PHONE_CONTACTS = 'RECEIVE_GET_PHONE_CONTACTS';
export const REQUEST_CREATE_CONTACTS = 'REQUEST_CREATE_CONTACTS';
export const RECEIVE_CREATE_CONTACTS = 'RECEIVE_CREATE_CONTACTS';
export const FAILURE_CREATE_CONTACTS = 'FAILURE_CREATE_CONTACTS';
export const REQUEST_GET_CHATS = 'REQUEST_GET_CHATS';
export const RECEIVE_GET_CHATS = 'RECEIVE_GET_CHATS';
export const FAILURE_GET_CHATS = 'FAILURE_GET_CHATS';
export const REQUEST_CREATE_CHAT = 'REQUEST_CREATE_CHATS';
export const RECEIVE_CREATE_CHAT = 'RECEIVE_CREATE_CHATS';

export const TOGGLE_SELECT_ROW = 'TOGGLE_SELECT_ROW';
export const RESET_PHONE_CONTACTS = 'RESET_PHONE_CONTACTS';
